# Generated by Django 3.0.8 on 2020-07-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarterbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel("Quarterbacks", "Quarterback")
    ]
